added e2e-test-setup
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

diff --git a/.github/workflows/e2e-test-setup.yml b/.github/workflows/e2e-test-setup.yml
--- a/.github/workflows/e2e-test-setup.yml
+++ b/.github/workflows/e2e-test-setup.yml
@@ -26,6 +26,18 @@ jobs:
 
       - name: Setup Notation
         uses: notaryproject/notation-action/setup@main
+    
+      - name: Setup Notation using unsupported version
+        id: unsupported-version
+        continue-on-error: true
+        uses: notaryproject/notation-action/setup@main
+        with:
+            version: unsupported
+      - name: 'Should Fail: Setup Notation using unsupported version'
+        if: steps.unsupported-version.outcome != 'failure'
+        run: |
+            echo "Setup Notation using unsupported version should fail, but succeeded."
+            exit 1
 
       - name: Setup Notation using URL
         uses: notaryproject/notation-action/setup@main
@@ -33,14 +45,39 @@ jobs:
             url: https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.6/notation_1.0.0-rc.6_linux_amd64.tar.gz
             checksum: bca21002cfb611f9ffc2930e88ecdb74471806770d0c64d45e39f4971692bcf5
 
-      - name: Setup Notation using URL but without checksum
+      - name: Setup Notation using URL without checksum
         id: no-checksum
         continue-on-error: true
         uses: notaryproject/notation-action/setup@main
         with:
           url: https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.6/notation_1.0.0-rc.6_linux_amd64.tar.gz
-      - name: 'Should Fail: Setup Notation using URL but without checksum'
+      - name: 'Should Fail: Setup Notation using URL without checksum'
         if: steps.no-checksum.outcome != 'failure'
         run: |
-            echo "Setup Notation using URL but without checksum should fail, but succeeded."
+            echo "Setup Notation using URL without checksum should fail, but succeeded."
+            exit 1
+    
+      - name: Setup Notation using URL and invalid checksum
+        id: invalid-checksum
+        continue-on-error: true
+        uses: notaryproject/notation-action/setup@main
+        with:
+          url: https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.6/notation_1.0.0-rc.6_linux_amd64.tar.gz
+          checksum: invalid
+      - name: 'Should Fail: Setup Notation using URL and invalid checksum'
+        if: steps.invalid-checksum.outcome != 'failure'
+        run: |
+            echo "Setup Notation using URL and invalid checksum should fail, but succeeded."
+            exit 1
+    
+      - name: Setup Notation using invalid URL
+        id: invalid-url
+        continue-on-error: true
+        uses: notaryproject/notation-action/setup@main
+        with:
+          url: invalid
+      - name: 'Should Fail: Setup Notation using invalid URL'
+        if: steps.invalid-url.outcome != 'failure'
+        run: |
+            echo "Setup Notation using invalid URL should fail, but succeeded."
             exit 1
