test
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

diff --git a/.github/workflows/e2e-test-setup.yml b/.github/workflows/e2e-test-setup.yml
--- a/.github/workflows/e2e-test-setup.yml
+++ b/.github/workflows/e2e-test-setup.yml
@@ -18,11 +18,8 @@ on:
   pull_request:
 
 jobs:
-  e2e-test-setup:
-    strategy:
-      matrix:
-        os: [ubuntu-latest, windows-latest]
-    runs-on: ${{ matrix.os }}
+  e2e-test-setup-linux:
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -68,6 +65,72 @@ jobs:
         with:
           url: https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.6/notation_1.0.0-rc.6_linux_amd64.tar.gz
           checksum: abcedf
+      - name: 'Should Fail: Setup Notation using URL and invalid checksum'
+        if: steps.invalid-checksum.outcome != 'failure'
+        run: |
+            echo "Setup Notation using URL and invalid checksum should fail, but succeeded."
+            exit 1
+    
+      - name: Setup Notation using invalid URL
+        id: invalid-url
+        continue-on-error: true
+        uses: Two-Hearts/notation-action/setup@fix
+        with:
+          url: invalid-url
+          checksum: test
+      - name: 'Should Fail: Setup Notation using invalid URL'
+        if: steps.invalid-url.outcome != 'failure'
+        run: |
+            echo "Setup Notation using invalid URL should fail, but succeeded."
+            exit 1
+  
+  e2e-test-setup-windows:
+    runs-on: windows-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      # E2E test cases on Notation: Setup
+      - name: Setup Notation
+        uses: Two-Hearts/notation-action/setup@fix
+    
+      - name: Setup Notation using unsupported version
+        id: unsupported-version
+        continue-on-error: true
+        uses: Two-Hearts/notation-action/setup@fix
+        with:
+            version: unsupported
+      - name: 'Should Fail: Setup Notation using unsupported version'
+        if: steps.unsupported-version.outcome != 'failure'
+        run: |
+            echo "Setup Notation using unsupported version should fail, but succeeded."
+            exit 1
+
+      - name: Setup Notation using URL
+        uses: Two-Hearts/notation-action/setup@fix
+        with:
+            url: https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.6/notation_1.0.0-rc.6_windows_amd64.zip
+            checksum: 3334f8884f3aefe3652fbae372a78aef72b1a449a380119b967c84dd0b075e2f
+
+      - name: Setup Notation using URL without checksum
+        id: no-checksum
+        continue-on-error: true
+        uses: Two-Hearts/notation-action/setup@fix
+        with:
+          url: https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.6/notation_1.0.0-rc.6_windows_amd64.zip
+      - name: 'Should Fail: Setup Notation using URL without checksum'
+        if: steps.no-checksum.outcome != 'failure'
+        run: |
+            echo "Setup Notation using URL without checksum should fail, but succeeded."
+            exit 1
+    
+      - name: Setup Notation using URL and invalid checksum
+        id: invalid-checksum
+        continue-on-error: true
+        uses: Two-Hearts/notation-action/setup@fix
+        with:
+          url: https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.6/notation_1.0.0-rc.6_windows_amd64.zip
+          checksum: abcdef
       - name: 'Should Fail: Setup Notation using URL and invalid checksum'
         if: steps.invalid-checksum.outcome != 'failure'
         run: |
