feat: timestamping (#80)
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

diff --git a/.github/workflows/e2e-test-sign.yml b/.github/workflows/e2e-test-sign.yml
--- a/.github/workflows/e2e-test-sign.yml
+++ b/.github/workflows/e2e-test-sign.yml
@@ -103,6 +103,20 @@ jobs:
             key=val
             foo=bar
       
+      - name: Sign artifact with timestamping
+        uses: ./sign
+        with:
+          plugin_name: e2e-test-plugin
+          plugin_url: https://github.com/notaryproject/notation-action/raw/e2e-test-plugin/tests/plugin_binaries/notation-e2e-test-plugin_0.1.0_linux_amd64.tar.gz
+          plugin_checksum: be8d035024d3a96afb4118af32f2e201f126c7254b02f7bcffb3e3149d744fd2
+          key_id: ${{ env.E2E_CERT }}
+          target_artifact_reference: ${{ env.target_artifact_reference }}
+          signature_format: cose
+          plugin_config: |-
+            keyFile=${{ env.E2E_KEY }}
+          timestamp_url: http://timestamp.digicert.com
+          timestamp_root_cert: ./tests/e2e/sign/tsaRootCert/DigiCertTSARootSHA384.cer
+      
       - name: Sign artifact with invalid plugin name
         continue-on-error: true
         id: invalid-plugin-name
@@ -218,6 +232,46 @@ jobs:
             echo "Sign artifact missing target artifact reference should fail, but succeeded."
             exit 1
       
+      - name: Sign artifact with timestamp url but no timestamp root cert
+        continue-on-error: true
+        id: missing-timestamp-root-cert
+        uses: ./sign
+        with:
+          plugin_name: e2e-test-plugin
+          plugin_url: https://github.com/notaryproject/notation-action/raw/e2e-test-plugin/tests/plugin_binaries/notation-e2e-test-plugin_0.1.0_linux_amd64.tar.gz
+          plugin_checksum: be8d035024d3a96afb4118af32f2e201f126c7254b02f7bcffb3e3149d744fd2
+          key_id: ${{ env.E2E_CERT }}
+          target_artifact_reference: ${{ env.target_artifact_reference }}
+          signature_format: cose
+          plugin_config: |-
+            keyFile=${{ env.E2E_KEY }}
+          timestamp_url: http://timestamp.digicert.com
+      - name: 'Should Fail: Sign artifact with timestamp url but no timestamp root cert'
+        if: steps.missing-timestamp-root-cert.outcome != 'failure'
+        run: |
+              echo "Sign artifact with timestamp url but no timestamp root cert should fail, but succeeded."
+              exit 1
+      
+      - name: Sign artifact with timestamp root cert but no timestamp url
+        continue-on-error: true
+        id: missing-timestamp-url
+        uses: ./sign
+        with:
+          plugin_name: e2e-test-plugin
+          plugin_url: https://github.com/notaryproject/notation-action/raw/e2e-test-plugin/tests/plugin_binaries/notation-e2e-test-plugin_0.1.0_linux_amd64.tar.gz
+          plugin_checksum: be8d035024d3a96afb4118af32f2e201f126c7254b02f7bcffb3e3149d744fd2
+          key_id: ${{ env.E2E_CERT }}
+          target_artifact_reference: ${{ env.target_artifact_reference }}
+          signature_format: cose
+          plugin_config: |-
+            keyFile=${{ env.E2E_KEY }}
+          timestamp_root_cert: ./tests/e2e/sign/tsaRootCert/DigiCertTSARootSHA384.cer
+      - name: 'Should Fail: Sign artifact with timestamp root cert but no timestamp url'
+        if: steps.missing-timestamp-url.outcome != 'failure'
+        run: |
+              echo "Sign artifact with timestamp root cert but no timestamp url should fail, but succeeded."
+              exit 1
+      
       - name: clean up plugin
         run: |
           notation plugin uninstall e2e-test-plugin --yes
@@ -236,3 +290,24 @@ jobs:
           signature_format: cose
           plugin_config: |-
             keyFile=${{ env.E2E_KEY }}
+      
+      - name: Sign artifact with timestamping using older Notation
+        continue-on-error: true
+        id: timestamping-with-older-notation
+        uses: ./sign
+        with:
+          plugin_name: e2e-test-plugin
+          plugin_url: https://github.com/notaryproject/notation-action/raw/e2e-test-plugin/tests/plugin_binaries/notation-e2e-test-plugin_0.1.0_linux_amd64.tar.gz
+          plugin_checksum: be8d035024d3a96afb4118af32f2e201f126c7254b02f7bcffb3e3149d744fd2
+          key_id: ${{ env.E2E_CERT }}
+          target_artifact_reference: ${{ env.target_artifact_reference }}
+          signature_format: cose
+          plugin_config: |-
+            keyFile=${{ env.E2E_KEY }}
+          timestamp_url: http://timestamp.digicert.com
+          timestamp_root_cert: ./tests/e2e/sign/tsaRootCert/DigiCertTSARootSHA384.cer
+      - name: 'Should Fail: Sign artifact with timestamping using older Notation'
+        if: steps.timestamping-with-older-notation.outcome != 'failure'
+        run: |
+              echo "Sign artifact with timestamping using older Notation should fail, but succeeded."
+              exit 1
